// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "getUser", input: never, result: User } | 
        { key: "health", input: never, result: string },
    mutations: 
        { key: "login", input: LoginData, result: string } | 
        { key: "register", input: LoginData, result: string },
    subscriptions: never
};

export type LoginData = { email: string; password: string }

export type User = { id: string; name: string | null; email: string; password: string }
